## NUMPY ARRAYS


In [3]:
import numpy as np 

Basic array creation , array generation function, random generation function, array attributes, array methods, reshaping and resizing

In [4]:
arr = np.array([1,2,3,4,5])

In [7]:
arr

array([1, 2, 3, 4, 5])

In [9]:
a = [1,2.5,3,4,5,'hello']
a

[1, 2.5, 3, 4, 5, 'hello']

In [10]:
np.array(a)

array(['1', '2.5', '3', '4', '5', 'hello'], dtype='<U32')

In [12]:
a = [1,2.5,3,4,5]
a

[1, 2.5, 3, 4, 5]

In [13]:
np.array(a)

array([1. , 2.5, 3. , 4. , 5. ])

Matricx

In [14]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
## 2 dimentional matricx
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [23]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

lins space

In [30]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Random generation function

In [32]:
np.random.rand(10)

array([0.24301334, 0.52565425, 0.9660397 , 0.66062352, 0.59175936,
       0.54509306, 0.50635084, 0.80306086, 0.41743526, 0.2034983 ])

In [33]:
np.random.randn(10)

array([ 0.42382152, -1.07123389, -0.77975448,  0.54581546, -0.12928105,
        0.30046663, -0.50916961,  0.53067436,  0.2671705 ,  0.02828816])

In [35]:
np.random.randint(10,20,10)

array([19, 13, 17, 14, 19, 12, 12, 18, 19, 11], dtype=int32)

array attributes

In [38]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.shape

(3, 3)

In [40]:
arr.size

9

In [41]:
arr.dtype

dtype('int64')

Array method

In [42]:
arr.min()

np.int64(1)

In [44]:
arr.max()

np.int64(9)

In [45]:
arr.sum()

np.int64(45)

In [52]:
np.sum(arr,axis = 0) #vertical

array([12, 15, 18])

In [53]:
np.sum(arr,axis=1) #horizontal

array([ 6, 15, 24])

In [54]:
arr.mean()

np.float64(5.0)

In [55]:
arr.std()

np.float64(2.581988897471611)

In [56]:
arr.argmax() #max value of index

np.int64(8)

In [57]:
arr.argmin() # min value of index

np.int64(0)

Reshape and resizing

In [58]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])