In [1]:
import numpy as np 

Numpy indexing and slicing of vectors, boolean indexing

In [8]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[6] # indexing

np.int64(17)

In [10]:
arr[1:5] # slicing

array([12, 13, 14, 15])

numpy indexing and slicing of matrix

In [12]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[3]

array([16, 17, 18, 19, 20])

In [22]:
arr[3,2] # indexing

np.int64(18)

In [24]:
arr[0:2,1:3] # slicing

array([[2, 3],
       [7, 8]])

In [26]:
arr[3:,3:] #slicing

array([[19, 20],
       [24, 25],
       [29, 30]])

boolean indexing

In [27]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
bool_index = arr % 2 == 0

In [29]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])