# array operations

arithmetic operations
broadcasting
deep and shallow copy
matrix operations
advance array manipulation 
stacking array
splitting array

In [1]:
import numpy as np 

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
arr = a1 + a2
arr

array([ 7,  9, 11, 13, 15])

In [4]:
arr2 = a1 - a2
arr2

array([-5, -5, -5, -5, -5])

In [5]:
arr3 = a1 * a2
arr3

array([ 6, 14, 24, 36, 50])

In [6]:
arr4 = a1 / a2
arr4

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
arr5 = a1 // a2
arr5

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [17]:
l = [1,2,3,4,5]
arr = np.array(l)

In [18]:
arr + 10

array([11, 12, 13, 14, 15])

In [21]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and shallow copy

In [24]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [27]:
slice = a[:5]
slice = slice * 10 
slice

array([10, 20, 30, 40, 50])

In [28]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
a[4:6] * 10

array([50, 60])

In [30]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
a
b = a 

In [39]:
b[0] = 99 # deep cosp

In [40]:
b

array([99, 10,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
a
b = a.copy() # shallow copy

In [43]:
b[1] = 10

In [44]:
b

array([99, 10,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [48]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [49]:
A

array([[1, 2],
       [3, 4]])

In [50]:
B

array([[5, 6],
       [7, 8]])

In [51]:
A @ B

array([[19, 22],
       [43, 50]])

In [52]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [53]:
A

array([[1, 2],
       [3, 4]])

In [54]:
A.T

array([[1, 3],
       [2, 4]])

In [57]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [60]:
v = np.vstack((a,b))
v

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [64]:
h = np.hstack((a,b))
h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Splitting array

In [67]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [72]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [73]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [74]:
for i in a:
    print(i)

1
2
3
4
5
